DEBUG:
  eval_in_train: 1
  eval_in_train_per_iter: -1
INPUT:
  #CLASSES: ['background', 'wall']
  CLASSES: ['background', 'wall', 'door', 'window']
  #SCENES: []
MODEL:
        #SEPERATE_CLASSES: ['wall']
  BACKBONE:
    OUT_CHANNELS: 128
  RPN:
    ANCHOR_SIZES_3D: [[0.4,1.5,1.5], [0.2,0.5,3], [0.4,1.5,3], [0.6,2.5,3]]
    YAWS:  (0, -1.57, -0.785, 0.785)
    RPN_SCALES_FROM_TOP: [4,3,2] 
    RPN_3D_2D_SELECTOR: [1,3,4,5]
    YAW_THRESHOLD: 0.7
    FG_IOU_THRESHOLD: 0.55 #  0.7
    BG_IOU_THRESHOLD: 0.2 # 0.3
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: (5,8,4)
    POOLER_SCALES_FROM_TOP: (4,3)
  LOSS:
    YAW_MODE: 'Diff'
SPARSE3D:
  nPlanesFront:  [32, 64, 64, 128, 128, 128, 256, 256, 256]
  KERNEL: [[2,2,2], [2,2,2], [2,2,2], [2,2,2], [2,2,2],[2,2,2],[2,2,2],[2,2,2]]
  STRIDE: [[2,2,2], [2,2,2], [2,2,2], [2,2,2], [2,2,2],[2,2,2],[2,2,2],[2,2,2]]
  VOXEL_FULL_SCALE: [2048, 2048, 512]  # [1536, 1536, 512 ]
  VOXEL_SCALE: 50
DATALOADER:
  SIZE_DIVISIBILITY: 6
SOLVER:
  EPOCHS: 100
  EPOCHS_BETWEEN_TEST: 1
  IMS_PER_BATCH: 1
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.000
  LR_STEP_EPOCHS: (80,)
  CHECKPOINT_PERIOD_EPOCHS: 10
  WARMUP_EPOCHS: 0.1
  TRACK_RUNNING_STATS: False
OUTPUT_DIR: "./RES/res_4c_fpn432_bs1_lr1"
TEST:
  IMS_PER_BATCH: 1
